cache_dir: /root/.cache/huggingface
log_dir: /workspace/Text2CAD/logs
checkpoint_path: /workspace/Text2CAD/Text2CAD_1.0.pth
prompt_file: null

text_encoder:
  text_embedder:
    model_name: "bert_large_uncased"
    max_seq_len: 512
    cache_dir: "/root/.cache/huggingface"
  adaptive_layer:
    in_dim: 1024
    out_dim: 1024
    num_heads: 8
    dropout: 0.1

cad_decoder:
  tdim: 1024
  cdim: 256
  num_layers: 8
  num_heads: 8
  dropout: 0.1
  ca_level_start: 2

test:
  batch_size: 1
  num_workers: 30
  prefetch_factor: 10
  log_dir: "/workspace/Text2CAD/logs"
  checkpoint_path: "/workspace/Text2CAD/Text2CAD_1.0.pth"
  nucleus_prob: 0
  sampling_type: "max"
  prompt_file: null

debug: False
info: "Inference"